config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homepages#homepage'

  resources :ppts do
    member do
      get :description
      get :a_first_page
      get :b_rules
      get :c_kick_off
      get :d_number
      get :e_auction
      get :f_challenge
      get :g_rap_contenders
      get :h_picture_contest
      get :i_guess_theme
      get :j_half_time
      get :k_return
      get :l_russian_roulette
      get :m_millionaire
      get :n_music
      get :o_second_half
      get :p_one_or_other
      get :q_backs
      get :r_song_rally
      get :s_end
    end
  end

  resources :playerones, only: [:destroy]
  resources :playertwos, only: [:destroy]

  resources :ppts, only: [:index, :new, :create, :show, :destroy] do
    resources :teamones, only: [:create, :destroy, :update] do
      resources :playerones, only: [:create]
    end
    resources :teamtwos, only: [:create, :destroy, :update] do
      resources :playertwos, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playerone.rb
class Playerone < ApplicationRecord
  belongs_to :teamone

  validates :name, presence: true
end

app/models/playertwo.rb
class Playertwo < ApplicationRecord
  belongs_to :teamtwo

  validates :name, presence: true
end

app/models/ppt.rb
class Ppt < ApplicationRecord
  has_one_attached :photo

  belongs_to :user

  has_one :teamone
  has_one :teamtwo

  has_many :playerones, through: :teamone
  has_many :playertwos, through: :teamtwo

  validates :name, presence: true
end

app/models/teamone.rb
class Teamone < ApplicationRecord
  belongs_to :ppt

  has_many :playerones

  validates :name, presence: true
end

app/models/teamtwo.rb
class Teamtwo < ApplicationRecord
  belongs_to :ppt

  has_many :playertwos

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ppts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def homepage
  end
end

app/controllers/playerones_controller.rb
class PlayeronesController < ApplicationController
  def create
    @ppt = Ppt.find(params[:ppt_id])
    @teamone = Teamone.find(params[:teamone_id])
    @playerone = Playerone.new(playerone_params)
    @playerone.teamone = @ppt.teamone
    @playerone.save
    redirect_to description_ppt_path(@ppt)
  end

  def destroy
    @playerone = Playerone.find(params[:id])
    @playerone.destroy
    @ppt = @playerone.teamone.ppt
    redirect_to description_ppt_path(@ppt)
  end

  private

  def playerone_params
    params.require(:playerone).permit(:name)
  end
end

app/controllers/playertwos_controller.rb
class PlayertwosController < ApplicationController
  def create
    @teamtwo = Teamtwo.find(params[:teamtwo_id])
    @ppt = @teamtwo.ppt_id
    @playertwo = Playertwo.new(playertwo_params)
    @playertwo.teamtwo = @teamtwo
    @playertwo.save
    redirect_to description_ppt_path(@ppt)
  end

  def destroy
    @playertwo = Playertwo.find(params[:id])
    @ppt = @playertwo.teamtwo.ppt
    @playertwo.destroy
    redirect_to description_ppt_path(@ppt)
  end

  private

  def playertwo_params
    params.require(:playertwo).permit(:name)
  end
end

app/controllers/ppts_controller.rb
class PptsController < ApplicationController
  before_action :find_ppt, only: [:show, :destroy, :description, :a_first_page, :b_rules, :c_kick_off, :d_number, :e_auction, :f_challenge, :g_rap_contenders, :h_picture_contest, :i_guess_theme, :j_half_time, :k_return, :l_russian_roulette, :m_millionaire, :n_music, :o_second_half, :p_one_or_other, :q_backs, :r_song_rally, :s_end]

  before_action :counter, only: []

  def index
    @ppts = Ppt.all.select do |ppt|
      ppt.user == current_user
    end
  end

  def new
    @ppt = Ppt.new
  end

  def create
    @ppt = Ppt.new(ppt_params)
    @ppt.user = current_user
    if @ppt.save
      redirect_to ppt_path(@ppt)
    else
      render :new
    end
  end

  def show
    @ppt_up = @ppt.name.upcase

    @teamone = Teamone.new
    @teamtwo = Teamtwo.new
  end

  def description
    @ppt_up = @ppt.name.upcase
    @teamone_name = @ppt.teamone.name.upcase
    @teamtwo_name = @ppt.teamtwo.name.upcase
    @playerone = Playerone.new
    @playertwo = Playertwo.new
    @playerones = @teamone.playerones
    @playertwos = @teamtwo.playertwos
  end

  def a_first_page
  end

  def b_rules
  end

  def c_kick_off
  end

  def d_number
    @playerones = @ppt.teamone.playerones
    @playertwos = @ppt.teamtwo.playertwos
    @player_number = @playerones.count + @playertwos.count
    @numbers = [1, 8, 9, 10, 13, 15, 333, 666, 15, 100].shuffle
    @random_number = @numbers[0..(@player_number - 1)]
  end

  def e_auction
  end

  def f_challenge
  end

  def g_rap_contenders
  end

  def h_picture_contest
    @themes = [1, 2, 3, 4, 5, 6].shuffle
    @theme = @themes[0]
  end

  def i_guess_theme
  end

  def j_half_time
  end

  def k_return
  end

  def l_russian_roulette
  end

  def m_millionaire
  end

  def n_music
  end

  def o_second_half
  end

  def p_one_or_other
  end

  def q_backs
  end

  def r_song_rally
  end

  def s_end
    if @teamone.point > @teamtwo.point
      @team_win = @teamone.name
    elsif @teamone.point == @teamtwo.point
      @team_win = "Egalité entre #{@teamone.name} et #{@teamtwo.name}"
    else
      @team_win =@teamtwo.name
    end
  end

  private

  def ppt_params
    params.require(:ppt).permit(:name, :photo)
  end

  def find_ppt
    @ppt = Ppt.find(params[:id])
    @teamone = @ppt.teamone
    @teamtwo = @ppt.teamtwo
  end

  def counter
    @teamone_counter = @ppt.teamone.point
    @teamtwo_counter = @ppt.teamone.point
  end
end

app/controllers/teamones_controller.rb
class TeamonesController < ApplicationController
  def create
    @ppt = Ppt.find(params[:ppt_id])
    @teamone = Teamone.new(teamone_params)
    @teamone.ppt = @ppt
    @teamone.save
    redirect_to ppt_path(@ppt)
  end

  def update
    @ppt = Ppt.find(params[:ppt_id])
    @teamone = @ppt.teamone
    @teamone.update(teamone_params)
  end

  def destroy
    @ppt = Ppt.find(params[:id])
    @teamone = Teamone.find(params[:ppt_id])
    @teamone.destroy
    redirect_to ppt_path(@ppt)
  end

  private

  def teamone_params
    params.require(:teamone).permit(:name, :point)
  end
end

app/controllers/teamtwos_controller.rb
class TeamtwosController < ApplicationController
  def create
    @ppt = Ppt.find(params[:ppt_id])
    @teamtwo = Teamtwo.new(teamtwo_params)
    @teamtwo.ppt = @ppt
    @teamtwo.save
    redirect_to ppt_path(@ppt)
  end

  def update
    @ppt = Ppt.find(params[:ppt_id])
    @teamtwo = @ppt.teamtwo
    @teamtwo.update(teamtwo_params)
  end

  def destroy
    @ppt = Ppt.find(params[:id])
    @teamtwo = Teamtwo.find(params[:ppt_id])
    @teamtwo.destroy
    redirect_to ppt_path(@ppt)
  end

  private

  def teamtwo_params
    params.require(:teamtwo).permit(:name, :point)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepages/homepage.html.erb
<div class="background homepage">
  <%= image_tag "Logo.png", class: "homepage-items" %>
  <h1 class="title homepage-items">PARTICPANTS PRENEZ PLACE</h1>
  <%= link_to "JOUER", new_ppt_path, class: "button-principal" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tropicoles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' if user_signed_in?%>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/ppts/a_first_page.html.erb
<h1>Bienvenue au ppt <%= @ppt.name %></h1>
<%= image_tag "beer.png" %>
<%= link_to "rules", b_rules_ppt_path %>

app/views/ppts/b_rules.html.erb
<% if @ppt.photo.attached?  %>
  <%= cl_image_tag @ppt.photo.key, class: "rules-photos" %>
<% else %>
  <%= image_tag "Logo.png", class: "photo_user" %>
<% end %>
<h3>Celui qui nous casse les couilles = un cul sec, Un bide = un cul sec
Visite au toilette => une galipette
À CHAQUE apparition de cette photo 2pt pour la team qui hurle en premier« Pirate ».
Bon esprit: 1 points bonus
Mauvais esprit: 1 points en moins
Corruption de l’arbitre autoriser si bien faite
L’arbitre compte les points</h3>
<%= link_to "rules", c_kick_off_ppt_path %>

<%= simple_form_for([@ppt, @teamone]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>
<%= simple_form_for([@ppt, @teamtwo]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>

app/views/ppts/challenge.html.erb
<h1>challenge sportif</h1>
<%= cl_image_tag @ppt.photo.key, class: "photo_user" %>
<h3>musique rocky</h3>

<h2>même page deux slides</h2>
<h2>defis 2</h2>
<h2>bring sally up</h2>

<h2>Defis 3</h2>
<h2>Gainage Festif</h2>
<h2>bring sally up</h2>

app/views/ppts/description.html.erb
<div class="background">
  <div class="title-page">
    <%= "#{@ppt_up} / players" %>
  </div>
  <div class="forms">
    <div class="form-ppt">
      <div class="title-medium">
      <%= @teamone_name %>
      </div>
      <div id="form-container" class="container">
        <%= simple_form_for([@ppt, @teamone, @playerone]) do |f| %>
          <div id="info" class="line">
            <div class="flex">
              <%= f.input :name, placeholder: "Team de fou" %>
              <div class="submit disappear">
                <%= f.submit "Submit", class: "button-submit-player" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <% @playerones.each do |playerone| %>
        <div class="player">
          <%= playerone.name %>
          <%= link_to playerone_path(playerone), method: :delete do %>
            <%= image_tag "trash.png" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="form-ppt">
      <div class="title-medium">
      <%= @teamtwo_name %>
      </div>
      <div id="form-container" class="container">
        <%= simple_form_for([@ppt, @teamtwo, @playertwo]) do |f| %>
          <div id="info" class="line">
            <div class="flex">
              <%= f.input :name, placeholder: "Team de fou" %>
              <div class="submit disappear">
                <%= f.submit "Submit", class: "button-submit-player" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <% @playertwos.each do |playertwo| %>
        <div class="player">
          <%= playertwo.name %>
          <%= link_to playertwo_path(playertwo), method: :delete do %>
            <%= image_tag "trash.png" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% if @playertwos.length == @playerones.length && @playertwos.length > 0 %>
    <div class="submit">
      <%= link_to "start", a_first_page_ppt_path(@ppt), class: "button-principal" %>
    </div>
  <% else %>
    <div class="submit">
      <h4 class= "button-principal">No Submit</h4>
    </div>
  <% end %>
</div>

app/views/ppts/e_auction.html.erb
<h1>Enchères</h1>
<%= link_to "rules", f_challenge_ppt_path %>

<%= simple_form_for([@ppt, @teamone]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>
<%= simple_form_for([@ppt, @teamtwo]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>

app/views/ppts/g_rap_contenders.html.erb
<h1>Rap Contenders</h1>
<h2>animations sympa / vidéo</h2>
<%= link_to "rules", h_picture_contest_ppt_path %>
<%= @teamone_counter %>
<%= @teamtwo_counter %>

<%= simple_form_for([@ppt, @teamone]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>
<%= simple_form_for([@ppt, @teamtwo]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>

app/views/ppts/h_picture_contest.html.erb
<h1>Concours Photos</h1>
<h2>Prenez une photo, le public vote. La photo gagnante rapporte 5 point
à l'équipe</h2>
<%= @theme %>
<%= link_to "rules", i_guess_theme_ppt_path %>

<%= simple_form_for([@ppt, @teamone]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>
<%= simple_form_for([@ppt, @teamtwo]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>

app/views/ppts/i_guess_theme.html.erb
<h1>l'équipe qui trouve la prochaine slide gagne 2 point, l'autre prend
cul-sec général</h1>
<%= link_to "rules", j_half_time_ppt_path %>
<%= @teamone_counter %>
<%= @teamtwo_counter %>

<%= simple_form_for([@ppt, @teamone]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>
<%= simple_form_for([@ppt, @teamtwo]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>

app/views/ppts/index.html.erb
<% if @ptts == [] %>
  <h1>CRÉÉ TON PREMIER PPT</h1>
  <%= link_to "jouer", new_ppt_path, class: "button-principal" %>
<% else %>
  <% @ppts.each do |ppt| %>
    <%= ppt.name %>
    <% if ppt.photo.attached? %>
      <%= cl_image_tag ppt.photo.key %>
    <% else %>
      <%= image_tag "Logo.png" %>
    <% end %>
    <%= link_to "ppt", ppt_path(ppt) %>
  <% end %>
<% end %>

app/views/ppts/kick_off.html.erb
<h1>Cul Sec</h1>
<p>vidéo twerk / culs sec qui arrive</p>
<%= image_tag "bar.jpg" %>
<%= link_to "rules", number_ppt_path %>
<% if @ppt.photo.attached?  %>
  <%= cl_image_tag @ppt.photo.key, class: "photo_user" %>
<% else %>
  <%= image_tag "Logo.png", class: "photo_user" %>
<% end %>

app/views/ppts/l_russian_roulette.html.erb
<h1>Roulette russe</h1>
<%= cl_image_tag @ppt.photo.key %>
<h3>Boire le verre et mentir à son adversaire pour qu’il ne devine pas son contenu
Si ton adversaire gagne boit un cul sec
Sinon 1 pts pour ton équipe
Et bien sur on le fait deux fois !
</h3>
<%= link_to "m_millionaire", m_millionaire_ppt_path %>

<%= simple_form_for([@ppt, @teamone]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>
<%= simple_form_for([@ppt, @teamtwo]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>

app/views/ppts/m_millionaire.html.erb
<h1>millions</h1>
<%= link_to "music", n_music_ppt_path %>

<%= simple_form_for([@ppt, @teamone]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>
<%= simple_form_for([@ppt, @teamtwo]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>

app/views/ppts/p_one_or_other.html.erb
<h1>l'un ou l'autre</h1>
<%= link_to "backs", q_backs_ppt_path %>

<%= simple_form_for([@ppt, @teamone]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>
<%= simple_form_for([@ppt, @teamtwo]) do |f| %>
  <div id="info" class="line">
    <%= f.input :point %>
    <div class="submit disappear">
      <%= f.submit "Submit", class: "button-submit" %>
    </div>
  </div>
<% end %>

app/views/ppts/rap_contenders.html.erb
<h1>Rap Contenders</h1>
<h2>animations sympa / vidéo</h2>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "Logo.png", class: "dropdown-toggle navbar_photo", id: "navbarDropdown", data: { toggle: "dropdown" } %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Home", root_path, class: "dropdown-item" %>
            <%= link_to "Personal", ppts_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>